manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: origin
      url-base: https://github.com/nRFCloud
  projects:
    - name: sdk-nrf
      path: nrf
      remote: nordic
      revision: v2.0.2
      import: true
  self:
    path: firmware
